# Generated by Django 4.2 on 2023-08-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_cart_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='note',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='phoneNumber',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
